<?php

return [
    'title' => 'SpeedZone Assistant',
    'open' => 'Open the assistant',
    'close' => 'Close the assistant',
    'reset' => 'Clear the conversation',
    'ready' => 'Ready',
    'thinking' => 'The assistant is thinking…',
    'placeholder' => 'Ask a question or request an action…',
    'greeting' => 'Hello :name,',
    'intro' => 'I can move an order through the workflow, produce an invoice, find an order or a driver, and read your delivery KPIs.',
    'currency' => 'MAD',
    'empty_reply' => 'Done.',

    'suggestions' => [
        'kpi' => 'What is the delivery success rate this week?',
        'search' => 'Find the orders for Casablanca',
        'invoice' => 'Generate the invoice for the last delivered order',
    ],

    'actions' => [
        'status_changed' => 'Status updated',
        'invoice_ready' => 'Invoice ready',
        'statement_ready' => 'Statement ready',
        'download' => 'Download',
        'results' => '{count} result found|{count} results found',
        'kpis' => 'Delivery KPIs',
    ],

    'search' => [
        'orders' => 'Orders',
        'drivers' => 'Drivers',
        'sellers' => 'Sellers',
        'customers' => 'Customers',
        'orders_count' => '{count} order|{count} orders',
    ],

    'kpis' => [
        'delivery_success_rate' => 'Success rate',
        'delivered_orders' => 'Delivered',
        'failed_deliveries' => 'Failed',
        'orders_in_period' => 'Orders',
        'in_transit' => 'In transit',
        'out_for_delivery' => 'Out for delivery',
        'returned_orders' => 'Returned',
        'average_delivery_time_hours' => 'Avg. delivery time',
        'revenue_in_period' => 'Revenue',
        'cash_to_collect' => 'Cash to collect',
        'top_drivers' => 'Top drivers',
        'delivered_count' => '{count} delivered',
        'hours' => ':value h',
    ],

    'errors' => [
        'disabled' => 'The assistant is not available on this instance.',
        'unavailable' => 'The assistant is temporarily unreachable. Please try again in a moment.',
        'busy' => 'The assistant has reached its usage quota. Please try again in a few seconds.',
    ],

    'pdf' => [
        'title' => 'INVOICE',
        'proforma_title' => 'STATEMENT',
        'proforma_notice' => 'Proforma — order not settled yet',
        'generated_on' => 'Generated on',
        'seller' => 'Seller',
        'recipient' => 'Recipient',
        'currency' => 'MAD',
        'footer' => 'Document generated by the SpeedZone assistant.',

        'columns' => [
            'description' => 'Description',
            'reference' => 'Reference',
            'date' => 'Date',
            'amount' => 'Amount',
            'delivery_service' => 'Parcel delivery service',
        ],

        'totals' => [
            'order_amount' => 'Order amount',
            'delivery_fee' => 'Delivery fee',
            'return_fee' => 'Return fee',
            'net' => 'Net to seller',
        ],
    ],
];
