<?php

return [
    'title' => 'Help Center & Partnership',

    'partnership' => [
        'page_title' => 'Partnership Contract & Terms',
        'intro' => 'The rules of collaboration between OWL Delivery and its partner sellers. They apply to every order entrusted to the platform.',

        'scope' => [
            'title' => 'Scope of the partnership',
            'summary' => 'What OWL Delivery handles, and what stays with the seller.',
            'points' => [
                'OWL Delivery handles pickup at the seller, inter-city transport, delivery to the end customer and cash collection on delivery.',
                'The seller remains responsible for the contents of the parcel, for it matching the order, and for its packaging.',
                'Every parcel must carry the label generated by the platform: an unlabelled parcel may be refused at pickup.',
                'The partnership carries no volume commitment and no minimum duration.',
            ],
        ],

        'pricing' => [
            'title' => 'Zone pricing grid',
            'summary' => 'Delivery fees depend on the destination city and sector.',
            'points' => [
                'The rate that applies is the one shown on the order when it was created: a grid revision is never applied retroactively.',
                'Intra-city deliveries are billed at the local zone rate; inter-city deliveries add the transfer cost of the zone involved.',
                'Remote zones and sectors outside the standard perimeter carry a surcharge, shown on the order.',
                'The amount collected from the customer (cash on delivery) is separate from the delivery fees and is paid back to you in full, less those fees.',
            ],
        ],

        'payouts' => [
            'title' => 'Payout terms and timing',
            'summary' => 'When and how the collected amount reaches your account.',
            'points' => [
                'Only orders in the "Delivered" status enter an invoice: an order still out for delivery is never paid in advance.',
                'Invoices are generated at the frequency configured on your account (weekly by default) and cover every order delivered in the period.',
                'Payout is made by bank transfer or by cheque, according to the payment method saved on your profile.',
                'Each invoice details, line by line, the amount collected, the delivery fees and the net payable.',
            ],
        ],

        'returns' => [
            'title' => 'Return fees and handling',
            'summary' => 'What happens, and what is billed, when a parcel cannot be delivered.',
            'points' => [
                'A refused or cancelled parcel, or one whose delivery has definitively failed, automatically enters the return circuit and is brought back to you.',
                'Return fees cover the journey back to the hub of your city; they are deducted from the invoice for the period concerned.',
                'The return follows six traceable steps, from hub receipt to hand-back in person. You can follow each step from the Returns section.',
                'You can correct the hand-back details while the return is in the "Created" or "Out for return" status.',
                'A return left unclaimed at the hub for thirty days may incur storage fees.',
            ],
        ],

        'liability' => [
            'title' => 'Liability for loss or damage',
            'summary' => 'The cover that applies, and its limits.',
            'points' => [
                'OWL Delivery is liable for the parcel from the moment it is collected until it is handed to the customer or returned to the seller.',
                'In case of proven loss, the parcel is compensated up to the value declared on the order, within the contractual ceiling.',
                'Damage is compensated on presentation of the order and the report drawn up at delivery, unless the packaging was manifestly insufficient.',
                'Perishable goods, fragile products not flagged as such, and undeclared valuables are excluded from cover.',
                'Any claim must be opened through a support ticket within forty-eight hours of the incident.',
            ],
        ],

        'obligations' => [
            'title' => 'Mutual commitments',
            'summary' => 'What each party guarantees the other.',
            'points' => [
                'The seller undertakes to provide accurate customer details: a wrong address or phone number is the single largest cause of failed delivery.',
                'OWL Delivery undertakes to keep the seller informed of every status change, in real time in the application.',
                'Either party may end the partnership at any time, subject to handling the parcels already in circulation.',
                'Any dispute is handled first by support; failing agreement, it falls to the competent courts.',
            ],
        ],
    ],

    'processes' => [
        'page_title' => 'Processes & Statuses',
        'intro' => 'The full journey of a parcel, status by status, with the role authorised to advance each step.',
        'tabs' => [
            'flows' => 'Journeys',
            'orders' => 'Order statuses',
            'returns' => 'Return statuses',
            'billing' => 'Billing',
        ],
        'legend_actor' => 'Changed by',
        'legend_permissions' => 'Permissions',
        'no_permission' => 'Automatic (no manual action)',
        'step_of' => 'Step {current} of {total}',
        'play' => 'Play the animation',
        'pause' => 'Pause',
        'replay' => 'Replay',
        'matrix' => [
            'status' => 'Status',
            'meaning' => 'What it means',
            'actor' => 'Who may change it',
            'permissions' => 'Required permissions',
        ],
        'transfer_types' => [
            'title' => 'Transfer manifest types',
            'summary' => 'When creating a manifest, the type chosen decides which parcels are offered for selection.',
        ],
    ],

    'flows' => [
        'success' => [
            'title' => 'Happy path',
            'summary' => 'From the registered order to the seller payout, without incident.',
            'invoiced' => [
                'label' => 'Invoiced',
                'description' => 'The delivered order enters the invoice for the period. The amount collected, less the delivery fees, is paid to the seller.',
                'actor' => 'Billing (automatic on generation)',
            ],
        ],
        'failure' => [
            'title' => 'Failure & return path',
            'summary' => 'Delivery fails: the parcel travels back to its seller through the reverse circuit.',
            'branch_title' => 'Return circuit',
            'branch_summary' => 'Six steps, from the delivery city back to the seller.',
        ],
    ],

    'billing' => [
        'seller' => [
            'title' => 'Seller invoice',
            'summary' => 'Computed automatically from the orders delivered in the period.',
            'collected' => 'Total collected from customers',
            'delivery_fees' => 'Delivery fees',
            'return_fees' => 'Return fees for the period',
            'payout' => 'Net payable to the seller',
            'note_delivered_only' => 'Only orders in the "Delivered" status are counted; orders still in flight stay pending.',
            'note_returns' => 'Orders handed back to the seller bring in no collection but do generate return fees.',
            'note_frequency' => 'The billing frequency is set on the seller profile.',
        ],
        'driver' => [
            'title' => 'Driver discharge',
            'summary' => 'What the driver owes the cash desk after his round.',
            'collected' => 'Cash collected on the round',
            'commission' => 'Driver commission',
            'due' => 'Amount owed to the cash desk',
            'note_discharge' => 'The discharge is built from the orders the driver delivered and collected on during the period.',
            'note_settlement' => 'Once the settlement is recorded, the discharge is marked as paid and drops out of later periods.',
        ],
    ],
];
