<?php

namespace App\Models;

use App\Casts\PaymentMethodCast;
use App\Enums\OrderFailureReason;
use App\Enums\OrderStatus;
use App\Enums\PartnerOrderStatus;
use App\Enums\PaymentMethod;
use App\Enums\TransferStatus;
use App\Models\Concerns\BelongsToStore;
use App\Models\Scopes\PartnerDeliveryVisibilityScope;
use Carbon\CarbonInterface;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\Relations\HasOne;

class Order extends Model
{
    use BelongsToStore;
    use HasFactory;

    /**
     * When true, outbound partner status sync is skipped (e.g. during inbound API ingestion).
     */
    public bool $suppressPartnerStatusSync = false;

    protected $fillable = [
        'tracking_number',
        'external_tracking_code',
        'partner_sync_error',
        'seller_id',
        'store_id',
        'partner_id',
        'driver_id',
        'assigned_at',
        'delivered_at',
        'returned_at',
        'pickup_request_id',
        'return_id',
        'invoice_id',
        'invoice_status',
        'customer_first_name',
        'customer_last_name',
        'customer_phone',
        'customer_address',
        'city_id',
        'sector_id',
        'payment_method',
        'order_value',
        'order_amount',
        'discount_amount',
        'delivery_price',
        'delivery_included',
        'total_amount',
        'notes',
        'is_fragile',
        'can_be_opened',
        'option_exchange',
        'status',
        'failure_reason',
        'failure_note',
        'failed_at',
        'failed_attempts_count',
        'is_returned',
    ];

    protected $casts = [
        'payment_method' => PaymentMethodCast::class,
        'status' => OrderStatus::class,
        'failure_reason' => OrderFailureReason::class,
        'failed_at' => 'datetime',
        'failed_attempts_count' => 'integer',
        'order_value' => 'decimal:2',
        'order_amount' => 'decimal:2',
        'discount_amount' => 'decimal:2',
        'delivery_price' => 'decimal:2',
        'total_amount' => 'decimal:2',
        'delivery_included' => 'boolean',
        'is_fragile' => 'boolean',
        'can_be_opened' => 'boolean',
        'option_exchange' => 'boolean',
        'is_returned' => 'boolean',
        'assigned_at' => 'datetime',
        'delivered_at' => 'datetime',
        'returned_at' => 'datetime',
    ];

    protected $appends = [
        'customer_full_name',
    ];

    protected static function booted(): void
    {
        static::saving(function (self $order): void {
            if (empty($order->status)) {
                $order->status = OrderStatus::CREATED->value;
            }

            // "No discount" is zero, not unknown, and the column says so. An
            // empty form field reaches the model as null once the framework has
            // converted it, which the database would reject outright.
            $order->discount_amount ??= 0;

            $payment = $order->payment_method instanceof PaymentMethod
                ? $order->payment_method
                : PaymentMethod::resolve((string) $order->payment_method);

            if ($payment === PaymentMethod::CASH) {
                $order->order_value = $order->order_amount;
            }

            $orderAmount = (float) ($order->order_amount ?? 0);
            $order->total_amount = round($orderAmount + $order->customerDeliveryShare(), 2);
        });
    }

    /*
    |--------------------------------------------------------------------------
    | Relationships
    |--------------------------------------------------------------------------
    */

    public function seller(): BelongsTo
    {
        return $this->belongsTo(User::class, 'seller_id');
    }

    /**
     * B2B partner this order was ingested from (null for native orders).
     */
    public function partner(): BelongsTo
    {
        return $this->belongsTo(Partner::class);
    }

    /**
     * Driver who delivered (or is assigned to deliver) this order.
     */
    public function driver(): BelongsTo
    {
        return $this->belongsTo(User::class, 'driver_id');
    }

    /**
     * Driver payment transactions generated by this order.
     */
    public function driverTransactions(): HasMany
    {
        return $this->hasMany(DriverTransaction::class);
    }

    public function pickupRequest(): BelongsTo
    {
        return $this->belongsTo(PickupRequest::class);
    }

    public function orderReturn(): BelongsTo
    {
        return $this->belongsTo(OrderReturn::class, 'return_id');
    }

    public function invoice(): BelongsTo
    {
        return $this->belongsTo(Invoice::class);
    }

    /**
     * Active return for this order (if any).
     */
    public function activeReturn(): ?OrderReturn
    {
        if ($this->relationLoaded('orderReturn')) {
            $return = $this->orderReturn;

            return $return && ! $return->isTerminal() ? $return : null;
        }

        return OrderReturn::query()
            ->where('order_id', $this->id)
            ->active()
            ->first();
    }

    public function transfers(): BelongsToMany
    {
        return $this->belongsToMany(Transfer::class, 'transfer_orders')
            ->withPivot('created_at');
    }

    /**
     * Active transfer this order belongs to (if any).
     */
    public function activeTransfer(): ?Transfer
    {
        return $this->transfers()
            ->whereNotIn('transfers.status', [TransferStatus::CANCELLED->value])
            ->first();
    }

    public function city(): BelongsTo
    {
        return $this->belongsTo(City::class);
    }

    public function sector(): BelongsTo
    {
        return $this->belongsTo(Sector::class);
    }

    /**
     * Depot this order ships out of, for the stock flow only.
     *
     * Deliberately absent from $fillable: it is derived from the shop at
     * creation, never submitted, and rewriting it would move a parcel to a
     * warehouse that has never held it.
     */
    public function stockHubCity(): BelongsTo
    {
        return $this->belongsTo(City::class, 'stock_hub_city_id');
    }

    public function statusHistories(): HasMany
    {
        return $this->hasMany(OrderStatusHistory::class)->orderBy('created_at')->orderBy('id');
    }

    public function latestStatusHistory(): HasOne
    {
        return $this->hasOne(OrderStatusHistory::class)->latestOfMany();
    }

    public function changeHistories(): HasMany
    {
        return $this->hasMany(OrderChangeHistory::class)->orderByDesc('created_at')->orderByDesc('id');
    }

    /**
     * Catalog lines picked from the vendor's stock.
     *
     * Empty for the parcel-only flow, where the seller declares an amount
     * without telling us what is inside the box.
     */
    public function items(): HasMany
    {
        return $this->hasMany(OrderItem::class)->orderBy('id');
    }

    /**
     * Whether this order was built from the vendor's stock.
     */
    public function isStockOrder(): bool
    {
        return $this->relationLoaded('items')
            ? $this->items->isNotEmpty()
            : $this->items()->exists();
    }

    /*
    |--------------------------------------------------------------------------
    | Helpers
    |--------------------------------------------------------------------------
    */

    /**
     * The part of the shipping cost the customer is asked for on top of the
     * goods, which is what separates `total_amount` from `order_amount`.
     *
     * When the seller advertises a delivered price, the customer pays the goods
     * and nothing more: the shipping is already baked into the figure he quoted.
     * The fee itself does not disappear — the seller still owes it to SpeedZone,
     * and BillingService keeps deducting it from what he is paid at invoicing.
     * This only decides who hands the money to the driver.
     */
    public function customerDeliveryShare(): float
    {
        return $this->delivery_included ? 0.0 : (float) $this->delivery_price;
    }

    /**
     * Whether this order was ingested from a B2B partner.
     */
    public function isPartnerDelivery(): bool
    {
        return $this->partner_id !== null;
    }

    /**
     * @return array<int, string>
     */
    public static function partnerDeliveryAllowedStatuses(): array
    {
        return PartnerOrderStatus::values();
    }

    /**
     * Record a status change in the order history.
     */
    public function recordStatus(
        OrderStatus|string $status,
        ?User $actor = null,
        ?string $comment = null,
        bool $isSystem = false,
        ?int $pickupRequestId = null,
        ?int $transferId = null,
        ?int $returnId = null,
        ?string $attachmentPath = null,
        ?string $attachmentName = null,
    ): OrderStatusHistory {
        return $this->statusHistories()->create([
            'status' => $status instanceof OrderStatus ? $status->value : $status,
            'user_id' => $isSystem ? null : $actor?->id,
            'is_system' => $isSystem,
            'comment' => $comment,
            'pickup_request_id' => $pickupRequestId,
            'transfer_id' => $transferId,
            'return_id' => $returnId,
            'attachment_path' => $attachmentPath,
            'attachment_name' => $attachmentName,
        ]);
    }

    /**
     * Public tracking URL encoded inside the QR code / shipping label.
     */
    public function trackingUrl(): string
    {
        $base = rtrim((string) config('orders.tracking_base_url', config('app.url')), '/');

        return $base.'/orders/'.$this->tracking_number;
    }

    public function getCustomerFullNameAttribute(): string
    {
        return trim("{$this->customer_first_name} {$this->customer_last_name}");
    }

    /**
     * Day the parcel reached its final stop: handed to the customer, or handed
     * back to the seller. Null while the order is still moving.
     */
    public function completedAt(): ?CarbonInterface
    {
        $status = $this->status instanceof OrderStatus ? $this->status : OrderStatus::tryFrom((string) $this->status);

        return $status === OrderStatus::RETURNED
            ? $this->returned_at
            : $this->delivered_at;
    }

    /*
    |--------------------------------------------------------------------------
    | Query scopes
    |--------------------------------------------------------------------------
    */

    /**
     * Restrict the query to orders owned by the given seller.
     */
    public function scopeOwnedBy(Builder $query, int $userId): Builder
    {
        return $query->where('seller_id', $userId);
    }

    /**
     * Restrict the query to orders assigned to the given driver.
     */
    public function scopeAssignedTo(Builder $query, int $userId): Builder
    {
        return $query->where('driver_id', $userId);
    }

    /**
     * Restrict the query to orders ingested from the given partner.
     */
    public function scopeForPartner(Builder $query, int $partnerId): Builder
    {
        return $query->where('partner_id', $partnerId);
    }

    /**
     * Partner deliveries visible to the given user (RBAC + driver assignment).
     */
    public function scopeVisibleForPartnerDeliveryAccess(Builder $query, User $user): Builder
    {
        return PartnerDeliveryVisibilityScope::applyToQuery($query, $user);
    }

    /**
     * Apply the global partner-delivery visibility scope for the current request.
     */
    public function scopeWithPartnerDeliveryVisibility(Builder $query): Builder
    {
        return $query->withGlobalScope('partnerDeliveryVisibility', new PartnerDeliveryVisibilityScope);
    }

    /**
     * Orders eligible to be settled on an invoice: delivered or returned and
     * not yet attached to any invoice.
     */
    public function scopeBillable(Builder $query): Builder
    {
        return $query
            ->whereNull('invoice_id')
            ->whereIn('status', [OrderStatus::DELIVERED->value, OrderStatus::RETURNED->value]);
    }

    public function scopeEligibleForPickup(Builder $query, int $sellerId): Builder
    {
        return $query
            ->where('seller_id', $sellerId)
            ->where('status', OrderStatus::CREATED)
            ->whereNull('pickup_request_id');
    }

    /**
     * City the parcel starts its journey from.
     *
     * The depot it was picked in for the stock flow, the vendor's own city for
     * the parcel-only flow where the goods begin at his door. Mirrored in SQL by
     * {@see self::scopeFromOriginCity()}.
     */
    public function originCityId(): ?int
    {
        if ($this->stock_hub_city_id) {
            return (int) $this->stock_hub_city_id;
        }

        $sellerCityId = $this->seller?->city_id;

        return $sellerCityId ? (int) $sellerCityId : null;
    }

    /**
     * The city behind {@see self::originCityId()}, for display.
     *
     * Reads whichever relation the caller loaded rather than querying, so a list
     * of a hundred parcels does not turn into a hundred round trips.
     */
    public function originCity(): ?City
    {
        return $this->stock_hub_city_id ? $this->stockHubCity : $this->seller?->city;
    }

    /**
     * Restrict to parcels whose journey starts in the given city.
     */
    public function scopeFromOriginCity(Builder $query, int $cityId): Builder
    {
        return $query->where(fn (Builder $q) => $q
            ->where('stock_hub_city_id', $cityId)
            ->orWhere(fn (Builder $parcelOnly) => $parcelOnly
                ->whereNull('stock_hub_city_id')
                ->whereHas('seller', fn (Builder $s) => $s->where('city_id', $cityId))));
    }

    /**
     * Orders ready to be grouped into an inter-city transfer.
     *
     * Two kinds of parcel wait at the same shelf. One was collected from the
     * vendor and signed into the depot of his city (IN_DEPOT); the other was
     * picked from his stock and packed there (PREPARED). Both are physically
     * sitting in a hub with nothing left to do but travel, so both belong here —
     * which is exactly what lets a prepared order ride along with the regular
     * ones, as the fulfilment flow requires.
     *
     * A prepared order bound for the city it is already in never reaches this
     * list: it left PREPARED for IN_DELIVERY_CITY the moment it was packed.
     */
    public function scopeEligibleForTransfer(Builder $query, ?int $fromCityId = null, ?int $toCityId = null): Builder
    {
        $query->whereIn('status', [OrderStatus::IN_DEPOT->value, OrderStatus::PREPARED->value])
            ->whereDoesntHave('transfers', fn (Builder $q) => $q->where(
                'transfers.status',
                '!=',
                TransferStatus::CANCELLED->value
            ))
            // A parcel with no known origin cannot be routed at all.
            ->where(fn (Builder $q) => $q
                ->whereNotNull('stock_hub_city_id')
                ->orWhereHas('seller', fn (Builder $s) => $s->whereNotNull('city_id')));

        if ($fromCityId) {
            $query->fromOriginCity($fromCityId);
        }

        if ($toCityId) {
            $query->where('city_id', $toCityId);
        }

        return $query;
    }

    public function getRouteKeyName(): string
    {
        return 'id';
    }
}
