<?php

namespace App\Models;

use App\Casts\PaymentMethodCast;
use App\Enums\OrderStatus;
use App\Enums\PartnerOrderStatus;
use App\Enums\PaymentMethod;
use App\Enums\TransferStatus;
use App\Models\Scopes\PartnerDeliveryVisibilityScope;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\Relations\HasOne;

class Order extends Model
{
    use HasFactory;

    /**
     * When true, outbound partner status sync is skipped (e.g. during inbound API ingestion).
     */
    public bool $suppressPartnerStatusSync = false;

    protected $fillable = [
        'tracking_number',
        'external_tracking_code',
        'partner_sync_error',
        'seller_id',
        'partner_id',
        'driver_id',
        'assigned_at',
        'delivered_at',
        'pickup_request_id',
        'return_id',
        'invoice_id',
        'invoice_status',
        'customer_first_name',
        'customer_last_name',
        'customer_phone',
        'customer_address',
        'city_id',
        'sector_id',
        'payment_method',
        'order_value',
        'order_amount',
        'delivery_price',
        'total_amount',
        'notes',
        'is_fragile',
        'can_be_opened',
        'option_exchange',
        'status',
        'is_returned',
    ];

    protected $casts = [
        'payment_method' => PaymentMethodCast::class,
        'status' => OrderStatus::class,
        'order_value' => 'decimal:2',
        'order_amount' => 'decimal:2',
        'delivery_price' => 'decimal:2',
        'total_amount' => 'decimal:2',
        'is_fragile' => 'boolean',
        'can_be_opened' => 'boolean',
        'option_exchange' => 'boolean',
        'is_returned' => 'boolean',
        'assigned_at' => 'datetime',
        'delivered_at' => 'datetime',
    ];

    protected $appends = [
        'customer_full_name',
    ];

    protected static function booted(): void
    {
        static::saving(function (self $order): void {
            if (empty($order->status)) {
                $order->status = OrderStatus::CREATED->value;
            }

            $payment = $order->payment_method instanceof PaymentMethod
                ? $order->payment_method
                : PaymentMethod::resolve((string) $order->payment_method);

            if ($payment === PaymentMethod::CASH) {
                $order->order_value = $order->order_amount;
            }

            $orderAmount = (float) ($order->order_amount ?? 0);
            $order->total_amount = round($orderAmount + (float) $order->delivery_price, 2);
        });
    }

    /*
    |--------------------------------------------------------------------------
    | Relationships
    |--------------------------------------------------------------------------
    */

    public function seller(): BelongsTo
    {
        return $this->belongsTo(User::class, 'seller_id');
    }

    /**
     * B2B partner this order was ingested from (null for native orders).
     */
    public function partner(): BelongsTo
    {
        return $this->belongsTo(Partner::class);
    }

    /**
     * Driver who delivered (or is assigned to deliver) this order.
     */
    public function driver(): BelongsTo
    {
        return $this->belongsTo(User::class, 'driver_id');
    }

    /**
     * Driver payment transactions generated by this order.
     */
    public function driverTransactions(): HasMany
    {
        return $this->hasMany(DriverTransaction::class);
    }

    public function pickupRequest(): BelongsTo
    {
        return $this->belongsTo(PickupRequest::class);
    }

    public function orderReturn(): BelongsTo
    {
        return $this->belongsTo(OrderReturn::class, 'return_id');
    }

    public function invoice(): BelongsTo
    {
        return $this->belongsTo(Invoice::class);
    }

    /**
     * Active return for this order (if any).
     */
    public function activeReturn(): ?OrderReturn
    {
        if ($this->relationLoaded('orderReturn')) {
            $return = $this->orderReturn;

            return $return && ! $return->isTerminal() ? $return : null;
        }

        return OrderReturn::query()
            ->where('order_id', $this->id)
            ->active()
            ->first();
    }

    public function transfers(): BelongsToMany
    {
        return $this->belongsToMany(Transfer::class, 'transfer_orders')
            ->withPivot('created_at');
    }

    /**
     * Active transfer this order belongs to (if any).
     */
    public function activeTransfer(): ?Transfer
    {
        return $this->transfers()
            ->whereNotIn('transfers.status', [TransferStatus::CANCELLED->value])
            ->first();
    }

    public function city(): BelongsTo
    {
        return $this->belongsTo(City::class);
    }

    public function sector(): BelongsTo
    {
        return $this->belongsTo(Sector::class);
    }

    public function statusHistories(): HasMany
    {
        return $this->hasMany(OrderStatusHistory::class)->orderBy('created_at')->orderBy('id');
    }

    public function latestStatusHistory(): HasOne
    {
        return $this->hasOne(OrderStatusHistory::class)->latestOfMany();
    }

    public function changeHistories(): HasMany
    {
        return $this->hasMany(OrderChangeHistory::class)->orderByDesc('created_at')->orderByDesc('id');
    }

    /*
    |--------------------------------------------------------------------------
    | Helpers
    |--------------------------------------------------------------------------
    */

    /**
     * Whether this order was ingested from a B2B partner.
     */
    public function isPartnerDelivery(): bool
    {
        return $this->partner_id !== null;
    }

    /**
     * @return array<int, string>
     */
    public static function partnerDeliveryAllowedStatuses(): array
    {
        return PartnerOrderStatus::values();
    }

    /**
     * Record a status change in the order history.
     */
    public function recordStatus(
        OrderStatus|string $status,
        ?User $actor = null,
        ?string $comment = null,
        bool $isSystem = false,
        ?int $pickupRequestId = null,
        ?int $transferId = null,
        ?int $returnId = null,
    ): OrderStatusHistory {
        return $this->statusHistories()->create([
            'status' => $status instanceof OrderStatus ? $status->value : $status,
            'user_id' => $isSystem ? null : $actor?->id,
            'is_system' => $isSystem,
            'comment' => $comment,
            'pickup_request_id' => $pickupRequestId,
            'transfer_id' => $transferId,
            'return_id' => $returnId,
        ]);
    }

    /**
     * Public tracking URL encoded inside the QR code / shipping label.
     */
    public function trackingUrl(): string
    {
        $base = rtrim((string) config('orders.tracking_base_url', config('app.url')), '/');

        return $base.'/orders/'.$this->tracking_number;
    }

    public function getCustomerFullNameAttribute(): string
    {
        return trim("{$this->customer_first_name} {$this->customer_last_name}");
    }

    /*
    |--------------------------------------------------------------------------
    | Query scopes
    |--------------------------------------------------------------------------
    */

    /**
     * Restrict the query to orders owned by the given seller.
     */
    public function scopeOwnedBy(Builder $query, int $userId): Builder
    {
        return $query->where('seller_id', $userId);
    }

    /**
     * Restrict the query to orders ingested from the given partner.
     */
    public function scopeForPartner(Builder $query, int $partnerId): Builder
    {
        return $query->where('partner_id', $partnerId);
    }

    /**
     * Partner deliveries visible to the given user (RBAC + driver assignment).
     */
    public function scopeVisibleForPartnerDeliveryAccess(Builder $query, \App\Models\User $user): Builder
    {
        return PartnerDeliveryVisibilityScope::applyToQuery($query, $user);
    }

    /**
     * Apply the global partner-delivery visibility scope for the current request.
     */
    public function scopeWithPartnerDeliveryVisibility(Builder $query): Builder
    {
        return $query->withGlobalScope('partnerDeliveryVisibility', new PartnerDeliveryVisibilityScope);
    }

    /**
     * Orders eligible to be settled on an invoice: delivered or returned and
     * not yet attached to any invoice.
     */
    public function scopeBillable(Builder $query): Builder
    {
        return $query
            ->whereNull('invoice_id')
            ->whereIn('status', [OrderStatus::DELIVERED->value, OrderStatus::RETURNED->value]);
    }

    public function scopeEligibleForPickup(Builder $query, int $sellerId): Builder
    {
        return $query
            ->where('seller_id', $sellerId)
            ->where('status', OrderStatus::CREATED)
            ->whereNull('pickup_request_id');
    }

    /**
     * Orders ready to be grouped into an inter-city transfer.
     * Pickup city = seller's city (from_city). Delivery city = order.city_id (to_city).
     */
    public function scopeEligibleForTransfer(Builder $query, ?int $fromCityId = null, ?int $toCityId = null): Builder
    {
        $query->where('status', OrderStatus::IN_DEPOT)
            ->whereDoesntHave('transfers', fn (Builder $q) => $q->where(
                'transfers.status',
                '!=',
                TransferStatus::CANCELLED->value
            ))
            ->whereHas('seller', fn (Builder $q) => $q->whereNotNull('city_id'));

        if ($fromCityId) {
            $query->whereHas('seller', fn (Builder $q) => $q->where('city_id', $fromCityId));
        }

        if ($toCityId) {
            $query->where('city_id', $toCityId);
        }

        return $query;
    }

    public function getRouteKeyName(): string
    {
        return 'id';
    }
}
